platform:ios, '8.0'
inhibit_all_warnings!
target ‘LogisticsApp’ do
 pod 'AFNetworking', '~> 3.1.0'
 pod 'Masonry','~>0.6.1'
 pod 'SDWebImage', '>= 4.0.0'
 pod 'IQKeyboardManager', '~> 3.3.7'  #兼容IOS7
 pod 'SCAdView' #廣告
 pod 'MJRefresh' #刷新
 pod 'MJExtension' #model解析
 pod 'JKRouter'
 pod ‘SDCycleScrollView’, ‘~> 1.75’

end
